theme: jekyll-theme-slate
name: scID
description: R library for identifying equivalent cell populations across single-cell RNA-sequencing data
higlighter: rogue
url: "https://batadalab.github.io/scID/"

permalink: pretty
